---
AWSTemplateFormatVersion: '2010-09-09'
Description: Building Lambda with AWS SDK, CloudFormation and AWS CLI
Resources:
  MyLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: "/aws/lambda/aws-sdk-iam-with-cloud-formation"
  IamRoleLambdaExecution:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
      - PolicyName:
          Fn::Join:
          - "-"
          - - dev
            - aws-sdk-iam-with-cloud-formation
            - lambda
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogStream
            Resource:
            - Fn::Sub: arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/aws-sdk-iam-with-cloud-formation:*
          - Effect: Allow
            Action:
            - logs:PutLogEvents
            Resource:
            - Fn::Sub: arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/aws-sdk-iam-with-cloud-formation:*:*
          - Effect: Allow
            Action:
            - iam:CreateUser
            - iam:DeleteUser
            - iam:ListUsers
            Resource:
            - Fn::Sub: arn:aws:iam::${AWS::AccountId}:user/*
      Path: "/"
      RoleName:
        Fn::Join:
        - "-"
        - - aws-sdk-iam-with-cloud-formation
          - dev
          - us-east-1
          - lambdaRole
  LambdaFunctionWithCF:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: 'serverless-cookbook'
        S3Key: original-serverless-cookbook-helloworld-lambda-0.0.1-SNAPSHOT.jar
      FunctionName: aws-sdk-iam-with-cloud-formation
      Handler: tech.heartin.books.serverlesscookbook.MyLambdaHandler::handleRequest
      MemorySize: 512
      Role:
        Fn::GetAtt:
        - IamRoleLambdaExecution
        - Arn
      Runtime: java8
      Timeout: 15
    DependsOn:
    - MyLogGroup
    - IamRoleLambdaExecution
